void init(){
//portB
	SYSCTL_RCGCGPIO_R |= 0x00000002; //SYSCTL_RCGCGPIO_R1 instead but it gives an ERROR!!
  while((SYSCTL_RCGCGPIO_R & 0x00000002) == 0 ) {};
	GPIO_PORTB_LOCK_R=0x4C4F434B;
	GPIO_PORTB_CR_R=0xFF;
	GPIO_PORTB_DIR_R |= 0xFF;   //all pins are output
	GPIO_PORTB_AFSEL_R =0;
	GPIO_PORTB_PCTL_R=0;
	GPIO_PORTB_AMSEL_R=0;
	GPIO_PORTB_DEN_R=0xFF;
	GPIO_PORTC_PUR_R=0;
}
